site_name: Tamerdocs Theme
site_url: http://anantshri.github.io/tamerdocs/
site_description: mkdocs theme for Tamerdocs
site_author: Anant Shrivastava
repo_url: https://github.com/anantshri/tamerdocs
copyright: Copyright &copy; <a href="https://anantshri.info">Anant Shrivastava</a>
theme_dir: tamerdocs
include_next_prev: false
extra:
  search: true
  twitter: https://www.twitter.com/anantshri
  facebook: https://www.facebook.com/Anantshri
  linkedin: https://www.linkedin.com/in/anantshri
